"""Create application tables

Revision ID: 9100c8420884
Revises: 
Create Date: 2025-12-30 21:36:00.753750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9100c8420884'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gdpr_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('export_file_url', sa.String(), nullable=True),
    sa.Column('deletion_scheduled_for', sa.TIMESTAMP(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.CheckConstraint("request_type IN ('export', 'deletion')", name='valid_request_type'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='valid_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gdpr_request_user_id'), 'gdpr_request', ['user_id'], unique=False)
    op.create_table('questionnaire_response',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('question_category', sa.String(), nullable=False),
    sa.Column('response_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("question_category IN ('software', 'hardware', 'aiml', 'goals')", name='valid_question_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_response_user_id'), 'questionnaire_response', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('skill_level', sa.String(), nullable=False),
    sa.Column('software_experience_years', sa.Integer(), nullable=True),
    sa.Column('programming_languages', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('python_proficiency', sa.String(), nullable=True),
    sa.Column('cpp_proficiency', sa.String(), nullable=True),
    sa.Column('ros_exposure', sa.Boolean(), nullable=False),
    sa.Column('hardware_experience', sa.String(), nullable=True),
    sa.Column('robotics_hardware', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sensor_integration_exp', sa.Boolean(), nullable=False),
    sa.Column('robot_deployment_exp', sa.Boolean(), nullable=False),
    sa.Column('ml_frameworks', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('computer_vision_exp', sa.Boolean(), nullable=False),
    sa.Column('llm_familiarity', sa.String(), nullable=True),
    sa.Column('career_objectives', sa.String(), nullable=True),
    sa.Column('robotics_domains_interest', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('learning_pace', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cpp_proficiency IN ('none', 'basic', 'intermediate', 'advanced') OR cpp_proficiency IS NULL", name='valid_cpp_proficiency'),
    sa.CheckConstraint("hardware_experience IN ('none', 'hobbyist', 'professional') OR hardware_experience IS NULL", name='valid_hardware_experience'),
    sa.CheckConstraint("learning_pace IN ('self-paced', 'structured', 'intensive') OR learning_pace IS NULL", name='valid_learning_pace'),
    sa.CheckConstraint("llm_familiarity IN ('none', 'basic', 'intermediate', 'advanced') OR llm_familiarity IS NULL", name='valid_llm_familiarity'),
    sa.CheckConstraint("python_proficiency IN ('none', 'basic', 'intermediate', 'advanced') OR python_proficiency IS NULL", name='valid_python_proficiency'),
    sa.CheckConstraint("skill_level IN ('beginner', 'intermediate', 'advanced')", name='valid_skill_level'),
    sa.CheckConstraint('software_experience_years >= 0 OR software_experience_years IS NULL', name='valid_experience_years'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True)
    op.drop_index('idx_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_conversations_session_id', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('page_context', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_conversations_session_id', 'conversations', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('selected_text_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying]::text[])", name='messages_role_check'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='messages_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_index('idx_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_questionnaire_response_user_id'), table_name='questionnaire_response')
    op.drop_table('questionnaire_response')
    op.drop_index(op.f('ix_gdpr_request_user_id'), table_name='gdpr_request')
    op.drop_table('gdpr_request')
    # ### end Alembic commands ###
